### ISSUE TITLE
Non-recoverable error on export with full Py suite

### ISSUE THREAD

**Issue by jontmy** [factoriolab/factoriolab-export#7]
Hi! I was checking out FactorioLab and with the recent update of Pyanodon's Alternative Energy I tried out the export with PyAL+AE (full Py, no other mods) to get a new data set.

On Factorio 1.1.72 (macOS) (with `--instrument-mod factoriolab-export`) this results in a non-recoverable error right as it begins to write the files:
```
The mod FactorioLab Export (1.0.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoriolab-export::on_string_translated (ID 153)
__factoriolab-export__/scripts/export-data.lua:550: attempt to concatenate field '?' (a nil value)
stack traceback:
	__factoriolab-export__/scripts/export-data.lua:550: in function 'export_data'
	__factoriolab-export__/control.lua:43: in function <__factoriolab-export__/control.lua:39>
```

The stack trace above can also be found in my [factorio-current.log](https://github.com/factoriolab/factoriolab-export/files/10137977/factorio-current.log).

**Comment by dcbroad3** [comment]
Thanks for the report. I'll try to look into this at some point. The error seems to indicate to me that Py is adding some pump and fluid named `?`, but the export tool is unable to find a name for either the pump or the fluid (or both).

**Comment by EzzaB** [comment]
I dug into this and there are several entities in pyAE called tidal-placer-mk01 etc (which are the place_result of tidal-mk01 etc). They do not have corresponding items. Line 550 (generating the lab_recipes) is looking up these entities in the flib item dictionary rather than the entity dictionary and changing this allows the export to succeed without crashing.

However loading the data up in the factoriolab web app doesn't work with the following error in the console:
```
error.service.ts:18 TypeError: Cannot read properties of undefined (reading 'speed')
    at RecipeUtility.adjustRecipe (recipe.utility.ts:106:19)
```
I think this is because there is no object for tidal-placer-mk01 etc in the items array in the data.json. tidal-mk01 does inherit the speed from its place_result tidal-placer-mk01 though.

Unfortunately I'm not familiar enough with flib, factoriolab or factorio modding in general to know what the correct solution is.

As far as I could tell these placeholder entities are destroyed immediately by script anyway so I manually removed the tidal-placer and numal-reef-placer references from the data.json and hash.json and that loads up and works.

**Comment by dcbroad3** [comment]
@EzzaB thanks for the info, it's funny I was just finally looking at this today, and my thought process was very similar. I think the 'correct' solution will require keeping track of what item the pump entity was found on, and using that item instead of the entity. Hope to get this resolved this week.
